### PR TITLE
update to latest zig master and run zig fmt:

### PR DESCRIPTION
**Pull request by g-w1**
* std.fs.File != std.net.Stream anymore

### CODE REVIEW

**Comment by g-w1** [comment]
Sorry for the formatting + content changes, my editor automatically runs fmt :(

**Comment by marler8997** [comment]
I'd really like to keep functional changes on separate commits from whitespace/formatting changes, it makes it much easier to manually review and verify the change in functionality is correct.

**Comment by g-w1** [comment]
Ok, ill look over the diff and do it in a different editor.

**Comment by g-w1** [comment]
Doing it now :P.

**Comment by g-w1** [comment]
See #5.

**Pull request closed without merging**
